VehicleTrackingSystem/Controllers/VehicleTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using VehicleTrackingSystem.DataModels;

namespace VehicleTrackingSystem.Controllers
{
    public class VehicleTypesController : Controller
    {
       private readonly VehicleTrackingSystemContext _context;

        public VehicleTypesController(VehicleTrackingSystemContext context)
        {
            _context = context;
        }

        // GET: VehicleTypes
        public async Task<IActionResult> Index()
        {
            return View(await _context.VehicleType.ToListAsync());
        }

        // GET: VehicleTypes/Details/5
        public async Task<IActionResult> Details(byte? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehicleType = await _context.VehicleType
                .FirstOrDefaultAsync(m => m.TypeId == id);
            if (vehicleType == null)
            {
                return NotFound();
            }

            return View(vehicleType);
        }

        // GET: VehicleTypes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: VehicleTypes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TypeId,TypeName")] VehicleType vehicleType)
        {
            if(IsTypeNameExistForAdd(vehicleType.TypeName)){
                ModelState.AddModelError("TypeName", "The vehicle type is already exist.");
            }
            if (ModelState.IsValid)
            {
                _context.Add(vehicleType);
                await _context.SaveChangesAsync();
                  return RedirectToAction(nameof(Index));
              //  return RedirectToAction("Create", "Vehicles");
            }
            return View(vehicleType);
        }

        // GET: VehicleTypes/Edit/5
        public async Task<IActionResult> Edit(byte? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehicleType = await _context.VehicleType.FindAsync(id);
            if (vehicleType == null)
            {
                return NotFound();
            }
            return View(vehicleType);
        }

        // POST: VehicleTypes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(byte id, [Bind("TypeId,TypeName")] VehicleType vehicleType)
        {
            if (id != vehicleType.TypeId)
            {
                return NotFound();
            }
            if (IsTypeNameForUpdate(vehicleType.TypeName,vehicleType.TypeId))
            {
                ModelState.AddModelError("TypeName", "The vehicle type name is already exist.");
            }
      
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(vehicleType);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VehicleTypeExists(vehicleType.TypeId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(vehicleType);
        }

        // GET: VehicleTypes/Delete/5
        public async Task<IActionResult> Delete(byte? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehicleType = await _context.VehicleType
                .FirstOrDefaultAsync(m => m.TypeId == id);
            if (vehicleType == null)
            {
                return NotFound();
            }

            return View(vehicleType);
        }

        // POST: VehicleTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(byte id)
        {
            var vehicleType = await _context.VehicleType.FindAsync(id);
            var isVehicleTypeInUse= _context.Vehicle.Where(v => v.TypeId == id).Any();
            if (isVehicleTypeInUse)
            {
                ModelState.AddModelError("TypeId", "The vehicle type is already in use.");
                return View(vehicleType);
            }
            
            _context.VehicleType.Remove(vehicleType);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VehicleTypeExists(byte id)
        {
            return _context.VehicleType.Any(e => e.TypeId == id);
        }
        private bool IsTypeNameExistForAdd(string typeName)
        {
            return _context.VehicleType.Any(v => v.TypeName == typeName);
        }
        private bool IsTypeNameForUpdate(string typeName, int typeId)
        {
            return _context.VehicleType.Where(v => v.TypeName == typeName && v.TypeId!=typeId).Any();
        }


    }
}

VehicleTrackingSystem/Controllers/VehiclesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using VehicleTrackingSystem.DataModels;

namespace VehicleTrackingSystem.Controllers
{
    public class VehiclesController : Controller
    {
      
        private readonly VehicleTrackingSystemContext _context;

        public VehiclesController(VehicleTrackingSystemContext context)
        {
            _context = context;
        }

        // GET: Vehicles
        public async Task<IActionResult> Index()
        {
            
            var vehicles = _context.Vehicle.Include(v => v.TireCondition).Include(v => v.VehicleType);
            //Condition cannot display, create IdNumber throw exception not handle

            return View(await vehicles.ToListAsync());
        }

        // GET: Vehicles/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehicle = await _context.Vehicle
                .Include(v => v.TireCondition)
                .Include(v => v.VehicleType)
                .FirstOrDefaultAsync(m => m.Vid == id);
            if (vehicle == null)
            {
                return NotFound();
            }

            return View(vehicle);
        }

        // GET: Vehicles/Create
        public IActionResult Create()
        {
            ViewData["ConditionId"] = new SelectList(_context.TireCondition, "ConditionId", "Condition");
            ViewData["TypeId"] = new SelectList(_context.VehicleType, "TypeId", "TypeName");
            return View();
        }

        // POST: Vehicles/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Vid,TypeId,FuelLevel,Idnumber,ConditionId,TireQty")] Vehicle vehicle)
        {
            if (IsVehicleExistforAdd(vehicle.Idnumber))
            {
                ModelState.AddModelError("Idnumber", "VIN/HIN already exists.");
            }
            if (ModelState.IsValid)
            {
                _context.Add(vehicle);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewData["ConditionId"] = new SelectList(_context.TireCondition, "ConditionId", "Condition", vehicle.ConditionId);
            ViewData["TypeId"] = new SelectList(_context.VehicleType, "TypeId", "TypeName", vehicle.TypeId);
            return View(vehicle);
        }
        
        // GET: Vehicles/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehicle = await _context.Vehicle.FindAsync(id);
            if (vehicle == null)
            {
                return NotFound();
            }
            ViewData["ConditionId"] = new SelectList(_context.TireCondition, "ConditionId", "Condition", vehicle.ConditionId);
            ViewData["TypeId"] = new SelectList(_context.VehicleType, "TypeId", "TypeName", vehicle.TypeId);
            return View(vehicle);
        }

        // POST: Vehicles/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Vid,TypeId,FuelLevel,Idnumber,ConditionId,TireQty")] Vehicle vehicle)
        {
            if (id != vehicle.Vid)
            {
                return NotFound();
            }
            if (IsVehicleExistforUpdate(vehicle.Idnumber,vehicle.Vid)){
                ModelState.AddModelError("Idnumber","The VIN/HIN is already exists.");
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(vehicle);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VehicleExists(vehicle.Vid))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ConditionId"] = new SelectList(_context.TireCondition, "ConditionId", "Condition", vehicle.ConditionId);
            ViewData["TypeId"] = new SelectList(_context.VehicleType, "TypeId", "TypeName", vehicle.TypeId);
            return View(vehicle);
        }

        // GET: Vehicles/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehicle = await _context.Vehicle
                .Include(v => v.TireCondition)
                .Include(v => v.VehicleType)
                .FirstOrDefaultAsync(m => m.Vid == id);
            if (vehicle == null)
            {
                return NotFound();
            }

            return View(vehicle);
        }

        // POST: Vehicles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var vehicle = await _context.Vehicle.FindAsync(id);
            _context.Vehicle.Remove(vehicle);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VehicleExists(int id)
        {
            return _context.Vehicle.Any(e => e.Vid == id);
        }

        private bool IsVehicleExistforAdd(string vin)
        {
            return _context.Vehicle.Where(v => v.Idnumber == vin).Any();
        }
        private bool IsVehicleExistforUpdate(string vin, int vID)
        {
            return _context.Vehicle.Where(v => v.Idnumber == vin && v.Vid != vID).Any();
        }
    }
}

VehicleTrackingSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Vehicle Tracking System</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Vehicles" asp-action="Index" class="navbar-brand">Vehicle Tracking System</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    <li><a asp-area="" asp-controller="Vehicles" asp-action="Index">Vehicles</a></li>
                    <li><a asp-area="" asp-controller="VehicleTypes" asp-action="Index">Vehicle Types</a></li>
                    <li><a asp-area="" asp-controller="TireConditions" asp-action="Index">Tire Conditions</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <div class="row">
                <div class="col-md-12">&copy; 2018 - Vehicle Tracking System</div>
            </div>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>